---
apiVersion: v1
kind: List
items:
  - apiVersion: tsb.tetrate.io/v2
    kind: Tenant
    metadata:
      name: eshop
      namespace: gitops-eshop-config
      annotations:
        tsb.tetrate.io/organization: tetrate
    spec:
      displayName: eShop Portal
  - apiVersion: tsb.tetrate.io/v2
    kind: Workspace
    metadata:
      name: eshop
      namespace: gitops-eshop-config
      annotations:
        tsb.tetrate.io/organization: tetrate
        tsb.tetrate.io/tenant: eshop
    spec:
      displayName: eShop Portal
      namespaceSelector:
        names:
        - "*/gitops-eshop"
        - "*/gitops-eshop-checkout"
        - "*/gitops-eshop-trafficgen"
  - apiVersion: tsb.tetrate.io/v2
    kind: Workspace
    metadata:
      name: payments
      namespace: gitops-eshop-config
      annotations:
        tsb.tetrate.io/organization: tetrate
        tsb.tetrate.io/tenant: eshop
    spec:
      displayName: Payments Gate
      namespaceSelector:
        names:
        - "*/gitops-eshop-payments"
  - apiVersion: gateway.tsb.tetrate.io/v2
    kind: Group
    metadata:
      name: eshop-gateways
      namespace: gitops-eshop-config
      annotations:
        tsb.tetrate.io/organization: tetrate
        tsb.tetrate.io/tenant: eshop
        tsb.tetrate.io/workspace: eshop
    spec:
      displayName: eShop Gateways
      namespaceSelector:
        names:
        - "*/gitops-eshop"
  - apiVersion: gateway.tsb.tetrate.io/v2
    kind: Group
    metadata:
      name: payments-gateways
      namespace: gitops-eshop-config
      annotations:
        tsb.tetrate.io/organization: tetrate
        tsb.tetrate.io/tenant: eshop
        tsb.tetrate.io/workspace: payments
    spec:
      displayName: Payments Gateways
      namespaceSelector:
        names:
        - "*/gitops-eshop-payments"
  - apiVersion: security.tsb.tetrate.io/v2
    kind: Group
    metadata:
      name: checkout-security
      namespace: gitops-eshop-config
      annotations:
        tsb.tetrate.io/organization: tetrate
        tsb.tetrate.io/tenant: eshop
        tsb.tetrate.io/workspace: eshop
    spec:
      displayName: Checkout Security
      namespaceSelector:
        names:
          - "*/gitops-eshop-checkout"
  - apiVersion: security.tsb.tetrate.io/v2
    kind: Group
    metadata:
      name: portal-security
      namespace: gitops-eshop-config
      annotations:
        tsb.tetrate.io/organization: tetrate
        tsb.tetrate.io/tenant: eshop
        tsb.tetrate.io/workspace: eshop
    spec:
      displayName: Portal Security
      namespaceSelector:
        names:
          - "*/gitops-eshop"
  - apiVersion: gateway.tsb.tetrate.io/v2
    kind: IngressGateway
    metadata:
      name: eshop-gateway
      namespace: gitops-eshop-config
      annotations:
        tsb.tetrate.io/organization: tetrate
        tsb.tetrate.io/tenant: eshop
        tsb.tetrate.io/workspace: eshop
        tsb.tetrate.io/gatewayGroup: eshop-gateways
    spec:
      displayName: eShop Gateway
      http:
      - hostname: eshop.tetrate.io
        name: eshop
        port: 80
        routing:
          rules:
          - route:
              host: gitops-eshop/products.gitops-eshop.svc.cluster.local
              port: 80
        rateLimiting:
          settings:
            rules:
              - dimensions:
                  - remoteAddress:
                      value: '*'
                limit:
                  requestsPerUnit: 3
                  unit: SECOND
      waf:
        rules:
          - Include @recommended-conf         # Recommended basic setup
          - SecRuleEngine On                  # Override DetectionOnly mode in @recommended-conf
          - SecResponseBodyAccess Off         # Override to not process response bodies
          - Include @crs-setup-conf           # Initialize the Core Rule Set
          - Include @owasp_crs/*.conf         # Load the Core Rule Set
          # Custom rule to deny requests with query parameter 'id=0'
          - SecRule ARGS:id "@eq 0" "id:1, phase:1,deny, status:403,msg:'Invalid id',log,auditlog"
      workloadSelector:
        labels:
          app: tsb-gateway-eshop
        namespace: gitops-eshop
  - apiVersion: gateway.tsb.tetrate.io/v2
    kind: IngressGateway
    metadata:
      name: payments-gateway
      namespace: gitops-eshop-config
      annotations:
        tsb.tetrate.io/organization: tetrate
        tsb.tetrate.io/tenant: eshop
        tsb.tetrate.io/workspace: payments
        tsb.tetrate.io/gatewayGroup: payments-gateways
    spec:
      displayName: Payments Gateway
      http:
      - hostname: payments.tetrate.io
        name: payments
        port: 80
        routing:
          rules:
          - route:
              host: gitops-eshop-payments/payments.gitops-eshop-payments.svc.cluster.local
              port: 80
      workloadSelector:
        labels:
          app: tsb-gateway-payments
        namespace: gitops-eshop-payments
  - apiVersion: tsb.tetrate.io/v2
    kind: Team
    metadata:
      name: everyone
      namespace: gitops-eshop-config
      annotations:
        tsb.tetrate.io/organization: tetrate
    spec:
      members:
      - organizations/tetrate/users/nacx
      - organizations/tetrate/users/zack
      - organizations/tetrate/users/wusheng
  - apiVersion: tsb.tetrate.io/v2
    kind: Team
    metadata:
      name: eshop-team
      namespace: gitops-eshop-config
      annotations:
        tsb.tetrate.io/organization: tetrate
    spec:
      members:
      - organizations/tetrate/users/zack
  - apiVersion: tsb.tetrate.io/v2
    kind: Team
    metadata:
      name: payments-team
      namespace: gitops-eshop-config
      annotations:
        tsb.tetrate.io/organization: tetrate
    spec:
      members:
      - organizations/tetrate/users/wusheng
  - apiVersion: rbac.tsb.tetrate.io/v2
    kind: Role
    metadata:
      name: tenant-reader
      namespace: gitops-eshop-config
    spec:
      displayName: Tenant Reader
      rules:
      - permissions:
        - READ
        types:
        - apiGroup: api.tsb.tetrate.io/v2
          kinds:
          - Tenant
  - apiVersion: rbac.tsb.tetrate.io/v2
    kind: AccessBindings
    metadata:
      name: eshop-tenant
      namespace: gitops-eshop-config
      annotations:
        tsb.tetrate.io/fqn: organizations/tetrate/tenants/eshop
    spec:
      allow:
      - role: rbac/creator
        subjects:
        - user: organizations/tetrate/users/nacx
      - role: rbac/tenant-reader
        subjects:
        - team: organizations/tetrate/teams/eshop-team
        - team: organizations/tetrate/teams/payments-team
  - apiVersion: rbac.tsb.tetrate.io/v2
    kind: AccessBindings
    metadata:
      name: payments-workspace
      namespace: gitops-eshop-config
      annotations:
        tsb.tetrate.io/fqn: organizations/tetrate/tenants/eshop/workspaces/payments
    spec:
      allow:
      - role: rbac/admin
        subjects:
        - user: organizations/tetrate/users/nacx
      - role: rbac/creator
        subjects:
        - team: organizations/tetrate/teams/payments-team
  - apiVersion: rbac.tsb.tetrate.io/v2
    kind: AccessBindings
    metadata:
      name: eshop-workspace
      namespace: gitops-eshop-config
      annotations:
        tsb.tetrate.io/fqn: organizations/tetrate/tenants/eshop/workspaces/eshop
    spec:
      allow:
      - role: rbac/admin
        subjects:
        - user: organizations/tetrate/users/nacx
      - role: rbac/creator
        subjects:
        - team: organizations/tetrate/teams/eshop-team
  - apiVersion: rbac.tsb.tetrate.io/v2
    kind: AccessBindings
    metadata:
      name: payments-gateways
      namespace: gitops-eshop-config
      annotations:
        tsb.tetrate.io/fqn: organizations/tetrate/tenants/eshop/workspaces/payments/gatewaygroups/payments-gateways
    spec:
      allow:
      - role: rbac/admin
        subjects:
        - team: organizations/tetrate/teams/payments-team
  - apiVersion: rbac.tsb.tetrate.io/v2
    kind: AccessBindings
    metadata:
      name: eshop-gateways
      namespace: gitops-eshop-config
      annotations:
        tsb.tetrate.io/fqn: organizations/tetrate/tenants/eshop/workspaces/eshop/gatewaygroups/eshop-gateways
    spec:
      allow:
      - role: rbac/admin
        subjects:
        - team: organizations/tetrate/teams/eshop-team
