---
apiVersion: v1
kind: List
items:
  - apiVersion: install.tetrate.io/v1alpha1
    kind: Gateway
    metadata:
      name: app-gw
      namespace: bookinfo
    spec:
      type: UNIFIED
      kubeSpec:
        service:
          type: LoadBalancer
  - apiVersion: gateway.tsb.tetrate.io/v2
    kind: Gateway
    metadata:
      name: app-bookinfo-gw
      namespace: bookinfo
      annotations:
        tsb.tetrate.io/organization: tetrate
        tsb.tetrate.io/tenant: dev
        tsb.tetrate.io/workspace: bookinfo-ws
        tsb.tetrate.io/gatewayGroup: bookinfo-gg
    spec:
      workloadSelector:
        namespace: bookinfo
        labels:
          app: app-gw
      http:
        - name: productpage
          port: 80
          hostname: "internal-bookinfo.tetrate.io"
          routing:
            rules:
              - route:
                  serviceDestination:
                    host: "bookinfo/productpage.bookinfo.svc.cluster.local"
                    port: 9080
  - apiVersion: traffic.tsb.tetrate.io/v2
    kind: ServiceRoute
    metadata:
      name: reviews-sr
      namespace: bookinfo
      annotations:
        tsb.tetrate.io/organization: tetrate
        tsb.tetrate.io/tenant: dev
        tsb.tetrate.io/workspace: bookinfo-ws
        tsb.tetrate.io/trafficGroup: bookinfo-tg
    spec:
      service: bookinfo/reviews.bookinfo.svc.cluster.local
      subsets:
      - name: v1
        labels:
          version: v1
      - name: v2
        labels:
          version: v2
      - name: v3
        labels:
          version: v3